# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if not .Values.gardenerManagedDNS.enabled }}
{{- if or ( eq .Values.serviceType "LoadBalancer" ) .Values.tlsConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  tls.crt: {{ required ".Values.tlsConfig.crt is required" .Values.tlsConfig.crt | b64enc }}
  tls.key: {{ required ".Values.tlsConfig.key is required" .Values.tlsConfig.key | b64enc }}
{{- end }}
{{- end }}
