# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.gardenerManagedDNS.enabled }}
    cert.gardener.cloud/secretname: {{ include "name" . }}-tls
    dns.gardener.cloud/dnsnames: {{ required ".Values.hostname is required" .Values.hostname }}
    dns.gardener.cloud/class: garden
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 10443
